### ISSUE TITLE
What is Target X Resolution?

### ISSUE THREAD

**Issue by Draghmar** [EverythingSmartHome/everything-presence-lite#123]
I don't understand this sensor. It gets different values although I've seen it mostly being at 360mm.

**Comment by detroitgoose** [comment]
@Draghmar I went searching all around for an explanation. Best I could come up with is that it seems to be a measure of how close two targets can be to each other before they are recognized as one single target.

I would appreciate corrections or clarification on this subject from a more knowledgeable source.

**Comment by Draghmar** [comment]
Thanks! I thought it could be that as that makes sense. I thought that maybe Lewis Barclay, seller and designer of this device, would know. ;)

**Comment by EverythingSmartHome** [comment]
Hello, sorry for the delay! Yes that is my understanding of it too, though I've very very rarely ever seen it change on this sensor so it's not really useful information. Sometimes you can configure the resolution at the sacrifice of distance but not on this sensor
