### ISSUE TITLE
Firmware upgrade via HA front end results in blinking led, no boot

### ISSUE THREAD

**Issue by kostasw** [EverythingSmartHome/everything-presence-lite#127]
I encountered this issue twice now, across both my Lite devices. The only way to revive them is to connect via USB and flash them from scratch from the user guide.
The issue then is that you need to re-onboard them in HA, go through the device and entity renaming anf reprogramming. Or am I doing something wrong?

**Comment by AlesAlitis** [comment]
> I encountered this issue twice now, across both my Lite devices. The only way to revive them is to connect via USB and flash them from scratch from the user guide. The issue then is that you need to re-onboard them in HA, go through the device and entity renaming anf reprogramming. Or am I doing something wrong?

I have the same issue. See https://github.com/EverythingSmartHome/everything-presence-lite/issues/128

**Comment by m4v3r1ckNl** [comment]
Same issue. See https://github.com/EverythingSmartHome/everything-presence-lite/issues/128#issuecomment-2268688481

**Comment by m4v3r1ckNl** [comment]
Resolved my issue by booting into macOS Monterey iso macOS Sonoma. The CH34xVSPDriver seems to be not working A-oke in Sonoma. Connected the EPL with USB on ESPHome (beta) page in HA, selected the "USB Serial (cu.wchusbserialfa410) - Paired" and reflashed the EPL with the previous .yaml file I downloaded previous.

![1  Screenshot 2024-08-16 at 13 22 52](https://github.com/user-attachments/assets/4c8961ad-673b-4318-b14a-950d0fc34be4)

![2 Screenshot 2024-08-16 at 13 34 12](https://github.com/user-attachments/assets/54b8a2cb-086f-4c3f-a428-c78ab08e2a1b)

![2a Screenshot 2024-08-16 at 13 34 35](https://github.com/user-attachments/assets/dd6a4c75-7021-450b-9566-ab45dc3071f8)

![2b Screenshot 2024-08-16 at 13 34 59](https://github.com/user-attachments/assets/c40a8b52-2a21-4f66-8329-6499d979fdc3)

![3 Screenshot 2024-08-16 at 13 13 20](https://github.com/user-attachments/assets/a773663a-ce34-4a87-afc1-7b8d7aaf5920)

![3a Screenshot 2024-08-16 at 13 35 30](https://github.com/user-attachments/assets/21d24f65-f2b6-44e6-a893-086f36e12285)

![4 Screenshot 2024-08-16 at 13 14 33](https://github.com/user-attachments/assets/8992b120-9570-4145-ab6a-5adae67283fe)

![5 Screenshot 2024-08-16 at 13 16 07](https://github.com/user-attachments/assets/66f05833-ea2d-4e32-85ea-637fb526cc84)

![6 Screenshot 2024-08-16 at 13 19 04](https://github.com/user-attachments/assets/e5f2dc3c-1f54-4f18-9eb3-8d0baf31670d)

![7 Screenshot 2024-08-16 at 13 19 36](https://github.com/user-attachments/assets/e50612a2-6339-4c63-a812-7b4e6d2593a5)

![8 Screenshot 2024-08-16 at 13 19 52](https://github.com/user-attachments/assets/02e435d3-b132-486c-84de-859f91dc035b)

![9 Screenshot 2024-08-16 at 13 39 16](https://github.com/user-attachments/assets/dcd85f46-a2cf-41fe-b222-4d87da5f1df6)

Hope this may help others.

**Comment by EverythingSmartHome** [comment]
Will close this in favour of https://github.com/EverythingSmartHome/everything-presence-lite/issues/128 which contains more details.
