### ISSUE TITLE
Feature Request - Exclusion Zones

### ISSUE THREAD

**Issue by TheManoeuvre** [EverythingSmartHome/everything-presence-lite#133]
As a EPLite user, it would be great if I could specify if any of the 4 zones are to be excluded from the overall occupancy sensor.

This should create a zone where Targets would not be reported, this would allow the user to set specific problem zones around items such as fans or 3D printers without having to set up complex zones around their perimeter.

**Comment by eatoff8** [comment]
Exclusion zone would be great. I have a screek sensor as well, and the exclusion zone makes is super easy to exclude an area that you know you're getting false positives from. Can see the zone on the little radar map card and everything, its pretty neat

**Comment by TheManoeuvre** [comment]
Yeah, I wish there was a way to easily visualize the targets and zones as angles and co-ordinates aren't simple to figure out. There may be a graph style card that could template this but I've not looked into it

**Comment by eatoff8** [comment]
> Exclusion zones should be fairly easy, will try to add.
> 
> Please checkout the new visual configurator add-on which helps to define zones :)
> 
> ![image](https://private-user-images.githubusercontent.com/53482654/374575967-8af97582-00c9-48ee-8078-32e3dbd84857.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MTM3MTMsIm5iZiI6MTcyODUxMzQxMywicGF0aCI6Ii81MzQ4MjY1NC8zNzQ1NzU5NjctOGFmOTc1ODItMDBjOS00OGVlLTgwNzgtMzJlM2RiZDg0ODU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDIyMzY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlODdhMDA3ZTU0NjY4YWY5MTM2NGM3Zjg1NDMzMWM0YzY0MTc1Nzg3Yjk1NzY4NjY4MTFkOTdlZjRjMjNkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nCVC2xbw7ySx9g7nzAu_tvejjK-A_QUXJvldNPLXsdg)
> 
> https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/creating-zones.html

That zone Configurator looks very slick, I'll give it a go tonight. Thanks for having a look at the exclusion zone, it means you can exclude an area of interference without having to move the other zones around it

**Comment by EverythingSmartHome** [comment]
Occupancy masks/Exclusion Zones added in https://github.com/EverythingSmartHome/everything-presence-lite/pull/218

Added to the mmWave Configurator Tool in https://github.com/EverythingSmartHome/everything-presence-addons/pull/9
