### ISSUE TITLE
Issue adding to ESPHome

### ISSUE THREAD

**Issue by clintebbesen** [EverythingSmartHome/everything-presence-lite#139]
I have added 4 lites to my home, I then went to add them to ESPHome so I can update to the latest firmware, however have run into issues as all 4 sensors have the same hostname. I managed to get one added and renamed the hostname, but the others are failing due to hostname length exceeded and then it's causing all kinds of issues after that. 

one issue I had was esphome picking a random sensor each time. For example, I adopted a sensor, I had no way to tell which one I was adopting so I just picked one and figured I'll rename it later when I work out which one it is. after adopting in the log I could see it was the sensor with ip address ending with 163, which was my bathroom sensor, so I renamed the hostname to bathroom, and then it reconciled, uploaded, but then after uploading the log showed an ip address ending in 168, so I had to rename a second time, but this time it worked as the first hostname rename gave it a unique one. I guess it failed because I told it to rename the hostname, it made a call out to the network to the old hostname (which there was 4 devices with that hostname), and the first one to respond was given the firmware. I don't know how it happened, I thought the would have different api keys, but either way something went wrong.

im working through solving them, but if there is any way for you to give them unique hostnames out of the box that would have prevented all these issues and adopting would have been quick and easy, instead its taking a few hours of fumbling around and troubleshooting issues. I would say lots of other people would go adding multiple sensors to their system at the same time without adding to ESPHome one by one as they add them to HA, and run into the same issue as me.

Edit: I have run into issues where the api key doesnt match and it won't install firmware, only resolution ive found is to edit the config and manually specify the ip address, so it uses that instead of the hostname when looking for the device to upload the firmware to.

**Comment by EverythingSmartHome** [comment]
I think there was a slight issue in the manufacturing build where this issue happened unfortunately. This should have been resolved in newer batches we think, but unfortunately not able to fix this for devices that were part of that batch. Hope that makes sense!
