### ISSUE TITLE
Uart blocking

### ISSUE THREAD

**Issue by svrooij** [EverythingSmartHome/everything-presence-lite#15]
I took the yaml from the repo, and added the web_server part, just to see the logs.

Every second the log shows an error:

```
20:01:18 | [W] | [component:214] | Component uart took a long time for an operation (0.12 s).
20:01:18 | [W] | [component:215] | Components should block for at most 20-30ms.
```

This means the firmware is taking too long to process the uart message. The duration varies between 0.08 and 0.12 according to the warning it should be around 0.03

will try to tweak the code tomorrow, to get the duration down.

**Comment by EverythingSmartHome** [comment]
I see this a lot with other components to, due to a recent ESPHome update - I don't think there is anything we can do about this for now. See this thread for a bunch of components that also do it:

https://github.com/esphome/issues/issues/4717
