### ISSUE TITLE
Unable to integrate in to Home assistant  

### ISSUE THREAD

**Issue by gazzaman22** [EverythingSmartHome/everything-presence-lite#151]
My EPLite failed yesterday so I reset the power  plugged in to my PC and tried to readopt it but Home assistant only see a ESPhome device now , any ideas or do I need to RMA it
Regards Garry

**Comment by EverythingSmartHome** [comment]
Can you share a screenshot of what your seeing? It sounds like you might have installed a blank firmware on it, if so please follow the factory reset section on the update page in the user guide

**Comment by gazzaman22** [comment]
![esp home](https://github.com/user-attachments/assets/f62b5c07-c772-42b4-b01a-560d2761d53a)
![discover](https://github.com/user-attachments/assets/6017ab90-39e3-4b38-8c41-1e0c78971446)
![Logs](https://github.com/user-attachments/assets/b56ba8ed-0e09-4a25-94fe-d948cf914687)
![wifi ok](https://github.com/user-attachments/assets/2cd969db-6684-4a9e-bd79-2b82a4e3b75a)
![config installed](https://github.com/user-attachments/assets/e7622ba0-85d2-47be-b169-70196f952412)
![first use](https://github.com/user-attachments/assets/cd5b6141-6a08-4a2a-9663-f1f81ed3c57d)

Hi I did follow the guide and this is what I get

**Comment by EverythingSmartHome** [comment]
Thanks for the screenshots, that's not the guide. The guide is located here: https://everythingsmarthome.github.io/everything-presence-lite/updating.html#manual-setup-and-factory-resetting

The method you are doing installs a blank ESPHome firmware to the device. Follow the steps above to install the Lite firmware to resolve the issues

**Comment by gazzaman22** [comment]
Hi you asked for screen shots of what I was seeing, I did use that guide and I cant get the firmware to install, my Home assistant does have Bluetooth but The EPlite isn't seeing it

**Comment by EverythingSmartHome** [comment]
> Hi you asked for screen shots of what I was seeing, I did use that guide and I cant get the firmware to install, my Home assistant does have Bluetooth but The EPlite isn't seeing it

I think you are possibly getting confused, the screenshots you sent were not from the user guide. The link I sent above is the guide, you do not need to click any other links or navigate to any other page other than the one I posted above. Are you clicking the big home assistant button on the page above as per the instructions? Then select the LD2450 sensor and then select either Bluetooth or no bluetooth

**Comment by gazzaman22** [comment]
Ok finally got it working, What was confusing me was the reference to the connect button , and once you pointed it out that its the home assistant icon that made more sense , also the button only seems to work for me 50% of the time and that's with Chome with no adds on any it works thanks for your help
