### ISSUE TITLE
I bought 5 EPLs and all give "Unknown" states. What am I w

### ISSUE THREAD

**Issue by sudoahidalgo** [EverythingSmartHome/everything-presence-lite#152]
![Screenshot 2024-08-29 9 38 30 AM](https://github.com/user-attachments/assets/d89b7986-a9f5-4563-beab-058ae4068893)

Did I configure this incorrectly? All 5 give the same data... only the ix metric is showing on all.

**Comment by EverythingSmartHome** [comment]
You have flashed a different firmware for a different mmWave sensor over the stock firmware. The default sensor is the LD2450, it looks like you've installed firmware for the LD2410 instead. Go back to the user guide and select the default option for the LD2450 and should be good to go

**Comment by sudoahidalgo** [comment]
Perfect.. its working now! Thanks!
