### ISSUE TITLE
Feature request - angle of installation 

### ISSUE THREAD

**Issue by simonlirwin** [EverythingSmartHome/everything-presence-lite#157]
The ideal placement for any sensor is the corner of a room to get the best coverage of corners of the room. 
However, all the zones are set up as "rectangles" in parallel with the sensor. If the sensor is placed at an angle all the zones would currently also be at an angle to the room, creating a lot of difficulty. So, the optimal zone setup means suboptimal room coverage. 
If we could set an angle of installation e.g. 45°, the x and y coordinates could be translated using trigonometry. Then all the zones can be aligned correctly with the room while also totally eliminating the blind corners.
This is something I don't think anybody else has done yet, and could give you a USP.

**Comment by LarsStegman** [comment]
Yeah, this would be awesome!

**Comment by EverythingSmartHome** [comment]
Now been added as of version 1.1.0
