### ISSUE TITLE
EPL assembly instructions use incorrect image for clicking the board into the case

### ISSUE THREAD

**Issue by oktay-sen** [EverythingSmartHome/everything-presence-lite#16]
[assembly.md in GitHub](https://github.com/EverythingSmartHome/everything-presence-lite/blob/f5c2f01c8b1381fc8ac11f2ca2443e603e984cd0/static/assembly.md#board-and-sensors) shows the correct image but the one on the website shows the case upside down:

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/3604645/806e9821-852e-42f1-9b91-d35de9a625ae)

I followed the website instructions and ended up not lining up the USB-C port with the hole on the case. This seems to be fixed on the `main` branch so probably just needs to be deployed 👍

**Comment by EverythingSmartHome** [comment]
Should be resolved now, thanks!
