### ISSUE TITLE
Home Assistant UI

### ISSUE THREAD

**Issue by tdashworth** [EverythingSmartHome/everything-presence-lite#17]
Loving it some far but missing the sensitivity control (I saw the Lite doesn't support). 

This is more of a question/feature. Are there any UI elements that provide a visual representation of a given space, where the zones are, and location of targets? 

This would be amazing for debugging and generally really cool!

**Comment by EverythingSmartHome** [comment]
Unfortunately there is no entity types in ESPHome/HA that would support that I don't think
