### ISSUE TITLE
How do I update esphome version on Lite?

### ISSUE THREAD

**Issue by sddgit** [EverythingSmartHome/everything-presence-lite#173]
I've added a Lite directly to HA, and it's working fine. It's flashed to firmware 1.0.10. I've updated esphome itself to 2024.9.1. My other 2 esphome devices are showing as having updates available (from 2024.8.1 to 2024.9.1), but the Lite isn't showing the update. How do I get esphome firmware updated on it?

**Comment by EverythingSmartHome** [comment]
What version of ESPHome does the lite show it's on?

**Comment by sddgit** [comment]
2024.8.3. The other 2 esphome devices that I have are on 2024.8.1, and showing that updates to 2024.9.1 are available.

Thank you for the reply.

**Comment by EverythingSmartHome** [comment]
Do you have the config adopted in ESPHome for the Lite? If so, you can just hit install and then wirelessly and it will update the version

**Comment by sddgit** [comment]
Esphome shows this for the three devices. The other 2 devices are showing the Update option, but not the Lite…
![IMG_0017](https://github.com/user-attachments/assets/eb6fc300-7acb-4717-97d6-ac14307ba140)

**Comment by EverythingSmartHome** [comment]
It can easily be because it's been compiled but not installed. Just hit install on the config

**Comment by sddgit** [comment]
OK, I installed and it went through the compile and installation process. Still showed as on 2024.8.3. But then I noticed HA said it needed reconfiguring, and that asked for a new encryption key. I grabbed that from the esphome config and all was well. Now shows 2024.9.1 as being installed. Any ideas why I had to go through this process? Thanks so much for the support.

**Comment by EverythingSmartHome** [comment]
Most likely when you first added it to Home Assistant, there is no encryption key. When you then add it to ESPHome, it automatically adds an encryption key for you (but isn't always obvious), meaning Home Assistant is still trying to communicate with the device without an encryption key while the device requires a key.
