### ISSUE TITLE
Unit of Measurement error log

### ISSUE THREAD

**Issue by TripelJ** [EverythingSmartHome/everything-presence-lite#18]
Hi,

I have now a lot of these in my log as you can see. Any suggestions on how to fix?

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:663
Integration: Sensor (documentation, issues)
First occurred: 19.46.00 (55 occurrences)
Last logged: 19.59.02

Entity sensor.everything_presence_lite_24e5fc_target_1_angle (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '°' which is not a valid unit for the device class ('distance') it is using; expected one of ['yd', 'mi', 'mm', 'm', 'cm', 'ft', 'km', 'in']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
Entity sensor.everything_presence_lite_24e5fc_target_2_angle (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '°' which is not a valid unit for the device class ('distance') it is using; expected one of ['yd', 'mi', 'mm', 'm', 'cm', 'ft', 'km', 'in']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
Entity sensor.everything_presence_lite_24e5fc_target_3_angle (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement '°' which is not a valid unit for the device class ('distance') it is using; expected one of ['yd', 'mi', 'mm', 'm', 'cm', 'ft', 'km', 'in']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22

**Comment by EverythingSmartHome** [comment]
Thanks, should be fixed now by: https://github.com/EverythingSmartHome/everything-presence-lite/pull/21
