### ISSUE TITLE
More errors in the log

### ISSUE THREAD

**Issue by TripelJ** [EverythingSmartHome/everything-presence-lite#19]
Hi Lewis,

The device is working, I'm just posting my findings here FYI if you can find it useful and something to tweak etc. Let me know if I should share differently. 

I haven't seen this message on any of my other esphome devices. 

[21:17:33][W][component:214]: Component uart took a long time for an operation (0.17 s).
[21:17:33][W][component:215]: Components should block for at most 20-30ms.

It's just a (yellow) warning.
Also in the core log I got this twice already. 

Logger: aioesphomeapi.connection
Source: runner.py:186
First occurred: 21.06.21 (2 occurrences)
Last logged: 21.15.54

everything-presence-lite-24e5fc @ 192.168.20.123: Connection error occurred: everything-presence-lite-24e5fc @ 192.168.20.123: EOF received. 

Don't know if it is related. Again don't have any connection errors to my other esphome devices. Running several sensors and Bluetooth proxies, energy meters etc. Just a thought. I noticed the config applies Bluetooth proxy as well default. I was told some time back that if you have a ESP32 board. You need to decide if you want to use it for Bluetooth or WiFi, if you enable both and there is a lot of traffic they will fight for the radio. And WiFi signal and connection can be greatly affected. Even making it hard to upload firmware over OTA and communicate with HA.

**Comment by EverythingSmartHome** [comment]
The component taking a long time message is "normal" now in ESPHome, see here for reference: https://github.com/esphome/issues/issues/4717

The Bluetooth thing is certainly true when using Arduino framework, it can make it difficult to complete updates and can be quite buggy, however the Lite uses ESP-IDF framework which improves performance a lot. Not saying there won't be any performance issues but if there are then do raise an issue.

If you consider that you can't really have bluetooth proxy enabled with ESPHome **without** using WiFi then the statement above doesn't make sense
