### ISSUE TITLE
How to setup Zones in Home Assistant Core

### ISSUE THREAD

**Issue by tomm1ed** [EverythingSmartHome/everything-presence-lite#191]
As I am using Home Assistant Core (in docker) I can't install Add-ons. Is the Everything Presence Zone Configurator available for HA Core as well? 
If not how can I manually calculate what to put in Zone X Begin, Zone Y Begin, Zone X End and Zone Y End?

**Comment by tomm1ed** [comment]
I tried using the values for Target 1 (me ;-) ) but whatever I do zone 2 always remains Clear:
<img width="475" alt="Scherm­afbeelding 2024-10-07 om 16 28 32" src="https://github.com/user-attachments/assets/3193760a-4810-41a2-bbbc-6acf2d4c6476">
Surely this should show Detected like Zone 1 which I created in the same way:
<img width="483" alt="Scherm­afbeelding 2024-10-07 om 16 30 54" src="https://github.com/user-attachments/assets/55ff8906-a3cd-467f-ba0f-00a7371b16af">

**Comment by EverythingSmartHome** [comment]
Glad you figured it out :) Yes the lower number needs to be the beginning X value and the higher number is the end X number.

The add-on is only compatible as a docker container, I don't think it would be possible to add it in Core.

**Comment by EverythingSmartHome** [comment]
No it's called Home Assistant Container. Home Assistant Core is the python package version.

There is no published version of the container yet but its planned

**Comment by tomm1ed** [comment]
> No it's called Home Assistant Container. Home Assistant Core is the python package version.
> 
> There is no published version of the container yet but its planned

A thanks, TIl :)

looking forward to the container version! Keep up the awesome work.
