### ISSUE TITLE
No Presence Detected?

### ISSUE THREAD

**Issue by boxgr0ve** [EverythingSmartHome/everything-presence-lite#2]
Set up all fine and added into HA - LED and LUX are working but all other values are displayed as 0.

Tried re-installing a couple of times but same issue.  (FYI the Troubleshooting, FAQ Update page takes you to the update for the EP1 if this makes a difference). I can confirm I have used the one for the EPL. 

Any other troubleshooting steps I can take, or is the LD2450 DOA?

EDIT: OK I'm an idiot - didn't realise I had to change the Max Distance from the default value of 0cm.  Changed to 200cm and now working as expected.

**Comment by EverythingSmartHome** [comment]
Great, glad you figured it out!
