### ISSUE TITLE
Detection issues

### ISSUE THREAD

**Issue by azerioxal** [EverythingSmartHome/everything-presence-lite#205]
I have two EP Lites I just managed to set up recently. Both of them have a weird issue where they constantly will clear the detection, only to immediately redetect. 
This occurs when there is someone present and it should be a solid uninterrupted detection.
I've tried messing with the off delay, but nothing seems to work.

Any ideas what could be causing this?
Thanks!

![Screenshot_20241009-160141.png](https://github.com/user-attachments/assets/d95f100c-54ba-4022-a743-4cbdb7ee5b94)

**Comment by EverythingSmartHome** [comment]
Which version of the firmware are you running?

**Comment by MenesesPT** [comment]
I've just noticed that I'm facing the same bug in the 1.1.1 version
