### ISSUE TITLE
Change the until of measurements from MM to IN

### ISSUE THREAD

**Issue by Mikede78** [EverythingSmartHome/everything-presence-lite#207]
Check the screen shots. You can see the Control area is setting MM and the other area is setting IN. How do I change that?

![Screenshot_20241009_183402_Chrome](https://github.com/user-attachments/assets/b9826a80-20b9-4b0f-87c6-241afea3bcd4)
![Screenshot_20241009_183345_Chrome](https://github.com/user-attachments/assets/9c8d8b98-337b-4cf8-b8b2-914fa8065ff8)

**Comment by EverythingSmartHome** [comment]
This is a Home Assistant setting. Click on the entity, hit the cog and then change unit of measurement. The default for all entities is mm, your HA might be changing it based on your general settings. I'd strongly advise keeping them all at mm

**Comment by Mikede78** [comment]
I can't find it. Is it on this screen?

[image: image.png]

**Comment by Mikede78** [comment]
Nevermind I found it. Thank you for your help.
