### ISSUE TITLE
Installation Angle setting not showing up in DEvice Dashboard

### ISSUE THREAD

**Issue by FCalleja** [EverythingSmartHome/everything-presence-lite#213]
I was following the setup guide from the QR code and noticed my Everything Presence Lite is not showing the slider for Installation Angle seen there, even when clicking to see all entities, this is all I see:
![image](https://github.com/user-attachments/assets/c939ec0d-e35b-4e7f-a7da-58e91fd7cd2b)

My expectation was to be able to adjust the Installation Angle slider seen in the guide here: https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/home-assistant-entities.html 
![home-assistant-entities-angle-controls](https://github.com/user-attachments/assets/f8b339bf-439c-4c3b-bc92-279247882571)

The firmware shows as up to date, so I'm not sure if something else is needed to configure this? I need it because my sensor is in a corner.

Any thoughts on what the problem might be?

**Comment by EverythingSmartHome** [comment]
Hello, do you have the ESPHome addon installed or no? If not, no need to install it I just need to know if you have it

**Comment by FCalleja** [comment]
Hi there! I do have the ESPHome addon installed. I do have an update, though, when I woke up this morning there were update notifications for both the EPL firmware and the configurator add-on, and I applied them and the installation angle is now there :) 

![image](https://github.com/user-attachments/assets/7b7c9f13-8221-4863-b0e9-0b0986d92cda)

Really happy with this sensor so far, thank you! closing the issue
