### ISSUE TITLE
Zone Configurator - Error Fetching Data

### ISSUE THREAD

**Issue by bazcurtis** [EverythingSmartHome/everything-presence-lite#214]
I have seeing this in the Zone Configurator. Any idea why that might be? It is working for my other EPL. I will reboot it later when I can a chance, but I thought I would mention it in case you have others report it.

Thanks so much for the Zone Configurator. It is so, so helpful.

<img width="679" alt="Screenshot 2024-10-19 at 16 16 00" src="https://github.com/user-attachments/assets/35704397-5f27-4910-a110-e4b0671e39a6">

**Comment by bazcurtis** [comment]
I have just rebooted it and still get the same error.

**Comment by MenesesPT** [comment]
I've faced the same problem, turns out I had disabled some entities in my HA. After I enabled them again it started working.

**Comment by bazcurtis** [comment]
Can you remember which ones? This EPL only has one zone.

**Comment by EverythingSmartHome** [comment]
You need to enable the other 3 zones (this is a home assistant feature) by clicking the entity, hitting the cog and then enable

**Comment by bazcurtis** [comment]
OK, thanks. Do you have plans for the tool to support one zone only? On my other EPL I only have 2 zones active and it works on that one.

**Comment by EverythingSmartHome** [comment]
It does support one zone only, you don't have to use the other zones just because the entities are enabled
