### ISSUE TITLE
ESP Home Add-on Page flashes only basic firmware on ESH Presence Lite with CO2 sensor.

### ISSUE THREAD

**Issue by CMDR-Sloma** [EverythingSmartHome/everything-presence-lite#215]
Hi,

I seem to have an endless loop of madness with ESH Lite and CO2 sensor.

Looks like adopting the device through ESP Home Add-on Page followed by firmware installation erases the version of the firmware with CO2 sensor support. Here are the steps to reproduce this:
1. Flash the firmware with CO2 sensor support on the Update Page.
2. Add WiFi SSID and password.
3. Add the device to HA through Integrations page.
4. Adopt the device on ESPHome Add-ons page.
5. Install of the firmware on ESP Home Add-on Page (as instructed by the pop-up.
6. Update of the encryption key.

Step 1 does flash correct firmware, while installation via Add-on Page flashes basic firmware and thus removes CO2 support. The solution is to go back to the update page and flash again firmware supporting CO2.

Is there a way to change config in the add-on page, so the correct firmware can be installed this way?

**Comment by EverythingSmartHome** [comment]
Thanks, was a bug, should be fixed now in https://github.com/EverythingSmartHome/everything-presence-lite/pull/217
