### ISSUE TITLE
High data usage

### ISSUE THREAD

**Issue by jamesgreeley** [EverythingSmartHome/everything-presence-lite#22]
Hi, is this normal 24hour data usage for the sensor? 

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/3008387/2195b6f6-92a4-48b7-aa71-e53444c5992c)

**Comment by openPhiL** [comment]
I can confirm that it is "high". 
![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/43743230/4cea5627-ccc1-4417-a7bf-c7aa351146bb)


Not sure if that is a problem, but compared to "the others", that is really high. 
I wonder if that is related to the issue that I have (but not yet raised) with Wifi-dropping, just tooo much?

**Comment by EverythingSmartHome** [comment]
I hadn't actually noted the data usage so thanks for bringing it up. I am seeing around 250mb's like @openPhiL screenshot above, but yours is almost double at 500. Do you happen to have it connected to 2 Home Assistant instances at the same time?

<img width="1745" alt="image" src="https://github.com/EverythingSmartHome/everything-presence-lite/assets/53482654/0082f2b8-4150-4c00-9589-6eec83d8fb9f">


The only thing I can think this would be related to is Bluetooth Proxy as it would constantly be sending scan results back to HA, something that's not yet enabled in the EP1 firmware.

**Comment by CDAutomate** [comment]
For what its worth mine are about ~250mb usage as well:

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/89545992/c7a00b6d-42cb-4ee8-b26c-5e5cc24164c2)

**Comment by openPhiL** [comment]
I tinkered a bit with the config and removed the information that I don't need: 
![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/43743230/461b271c-0192-4fcc-8b85-d663b7fa53e8)

that boils down the data submitted to around 7MB / day: 
![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/43743230/141222e4-b3cb-4dac-bb2b-fcc97ef0c9d8)

So if that is an issue for you, you may use this to fix, just as an inspiration. 

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/43743230/5df3d0b9-680e-4276-8d79-4e447dcda7ca)

Which leads me to think, if you have lots of sensors, you will have lots of data. hence, this is not "an issue" to fix and this can be closed, what do you think?

**Comment by EverythingSmartHome** [comment]
Thanks for sharing the findings!
