### ISSUE TITLE
EP Lite became unavailable out of the blue

### ISSUE THREAD

**Issue by Lampornis** [EverythingSmartHome/everything-presence-lite#220]
When I got up this morning my kitchen lights automation tied to the EP Lite fired off as expected.  Then, 15 minutes later the EPL went unavailable.  Tried all the normal stuff to get it working again (rebooted HA, clean build file install in ESPHome, etc) but none of that has worked.  Tried to look at the logs but it appears there is some sort of communication issue that I do not know how to resolve.  I've attached illustrating the error messages I have recieved both with trying to get the logs and when I tried to do a clean file install.  Oddly, ESPHome did an update this morning and the EPL updated just fine (after it went unavailable).  ESPHome shows the EPL as being online.
![CleanShot 2024-10-22 at 08 06 20@2x](https://github.com/user-attachments/assets/7fa72b99-9493-4471-b305-3d984fc56692)
![CleanShot 2024-10-22 at 08 11 51@2x](https://github.com/user-attachments/assets/5defe2c2-bb23-4a8f-91e8-8e91809608d4)

**Comment by EverythingSmartHome** [comment]
Not really possible to tell from these logs unfortunately as could be many things. Are you able to check logs over USB?

**Comment by Lampornis** [comment]
Never mind.  Gosh, when I took my computer upstairs to plug it into the EPL to get the logs HA decided to inform me that I needed to re-enter the encryption key.  Would have been nice had they just told me before I spend the last hour and half trying to figure this out.
