### ISSUE TITLE
Inactive target = zero distance

### ISSUE THREAD

**Issue by ChronSyn** [EverythingSmartHome/everything-presence-lite#236]
Recently got my first EP Lite. It came with firmware 1.0.6 installed, and I decided to update to 1.2.0 fairly quickly.

What I've noticed is that 'target active' statuses completely stop 'target distance' measurements. For example, if I'm sat perfectly still, the active state turn off after a short time, and the distance measurement will drop to 0 until I move. 'Detection' is still on however, so it knows I'm there.

The first problem with this is that it makes defining zones very difficult, especially as the 'Zone Design Tool' doesn't appear to be available for Docker versions of HA.

The second problem with this is that just because a target is inactive, they don't suddenly disappear into thin air.
The sensor knows I'm there, it knows I'm not moving, but it somehow thinks I'm 0mm away from it.

Is there a way to change this behavior?

I strongly feel that 'detection + distance' should be linked, rather than 'active + distance'. An even better option would be a toggle, to allow users to choose which behavior they prefer.

I'm not unfamiliar with ESPHome or writing code for devices, but I don't even know which sensor is inside my unit, so I'm not sure which yaml files I need.

**Comment by EverythingSmartHome** [comment]
Are you sure that the sensor is actually showing as detected and your not running into the occupancy cooldown period? Once a target disappears, it will keep occupancy detected for whatever setting you have it set to. Hopefully that makes sense?

The zone configurator is very much available for docker: https://hub.docker.com/r/everythingsmarthome/everything-presence-mmwave-configurator
