### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by citarone** [EverythingSmartHome/everything-presence-lite#247]
![Screenshot 2024-11-27 122548](https://github.com/user-attachments/assets/479adba2-33f4-45e6-971c-ce74ff573025)
It doesn't work at all—no recognition when I'm standing in front of it, moving, or doing anything else. The detection range is set to 100 cm, but it occasionally detects ghosts, while it doesn't recognize me at all. I want to set it up, configure it, and then forget about it—not spend forever tinkering with it just to maybe get it working. Now I've spent 50 euros for nothing.

**Comment by citarone** [comment]
do you mean this 
![Screenshot 2024-11-27 123149](https://github.com/user-attachments/assets/1cb9dfa3-e32a-4fb1-9e51-12ee4633cfcb)

**Comment by EverythingSmartHome** [comment]
Yes please, plus all the settings below that too.

Can you advise order number?

**Comment by citarone** [comment]
my oder number is #EST22125  

I didn’t change anything, and now it seems to be working. I have no idea why it suddenly works. so sorry for my rant 
![Screenshot 2024-11-27 130605](https://github.com/user-attachments/assets/8339f51b-7c37-4458-bfbf-a3942e132c0a)
