### ISSUE TITLE
Everything Presence Lite - Zone Configurator - Docker documentation

### ISSUE THREAD

**Issue by keithellis74** [EverythingSmartHome/everything-presence-lite#249]
The documentation here: https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/creating-zones.html#using-the-add-on 
provides a suggested docker compose file for a standalone docker install. The ```image``` path is incorrect, the correct ```image``` path should be as follows:
```image: everythingsmarthome/everything-presence-mmwave-configurator:latest```

**Comment by jonny190** [comment]
Just found the same, came to log it haha

**Comment by jonny190** [comment]
I've created a PR https://github.com/EverythingSmartHome/everything-presence-lite/pull/250

**Comment by EverythingSmartHome** [comment]
Thank you!
