### ISSUE TITLE
Everything Presence Lite boot loop after update

### ISSUE THREAD

**Issue by woniol** [EverythingSmartHome/everything-presence-lite#255]
Hi,
After update to the latest version Everything Presence Lite falls into kind of boot look, no connection to HA possible.
I attache the log file., asking for help.
[esp-web-tools-logs (5).txt](https://github.com/user-attachments/files/17959647/esp-web-tools-logs.5.txt)

**Comment by EverythingSmartHome** [comment]
This is an unintentional bug in ESPHome that causes a boot loop when internet is blocked or unaccessible when it tries to check for updates on GitHub

**Comment by woniol** [comment]
Is there a way to disable updates check?

**Comment by woniol** [comment]
As mentioned in other thread, proper DNS1 setup helped here.
