### ISSUE TITLE
Unable to detect motion with LD2450

### ISSUE THREAD

**Issue by kostda** [EverythingSmartHome/everything-presence-lite#26]
Hello two days ago I recieved your sensor, but I'm unable to make it work, since that day.
Light sensor is working, but occupancy is not.

What i tried:
1) make sure to have sensor properly connected
2) update ESPHome in HA
3) update ESPHome in Everything presense lite
4) install firmware multiple times at https://everythingsmarthome.github.io/everything-presence-lite/updating.html
5) tried multiple cables and power bricks
6) tried set different settings inside HA and restarted multiple times

This image shows how its connected:
![IMG_20231102_230027](https://github.com/EverythingSmartHome/everything-presence-lite/assets/54975513/28cf91b7-7463-4a52-b0ca-e6437c7ceee7)

Here is preview of settings inside HA:
![2023-11-02_23-01](https://github.com/EverythingSmartHome/everything-presence-lite/assets/54975513/60a7124b-383e-47f8-a4bb-98dceb20ce44)

Here is log from ESPHome:
[logs_everything-presence-lite-24e71c_logs.txt](https://github.com/EverythingSmartHome/everything-presence-lite/files/13245009/logs_everything-presence-lite-24e71c_logs.txt)

Thanks for any help

**Comment by EverythingSmartHome** [comment]
Hello, it looks like from your logs that the sensor is working correctly but I notice in your screenshot that you have the distance set to a maximum of 10cm which would explain why you aren't seeing anything?

**Comment by kostda** [comment]
Thanks for quick response!

Sorry for that. As I said, I was experimenting with settings to try if anything change. Even with maximum value its not working.

When device is restarted it shows as motion is detected but after few seconds it shows no motion and Im unable to detect it.
![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/54975513/cc36bd6c-d13e-4c05-8f5a-4877e33047c8)

**Comment by EverythingSmartHome** [comment]
Can you post some updated logs with the distance set correctly?

**Comment by kostda** [comment]
Here it is:
[logs_everything-presence-lite-24e71c_logs (2).txt](https://github.com/EverythingSmartHome/everything-presence-lite/files/13247222/logs_everything-presence-lite-24e71c_logs.2.txt)

**Comment by EverythingSmartHome** [comment]
Strange as it seems like it is updating. What you can try next is download the "HLKRadarTool" app on iOS or Android and try to update the firmware of the mmWave sensor. Once you open the app it will discover it over bluetooth and give you the option to update firmware

**Comment by kostda** [comment]
It looks like I have latest formal version.

Should I try to install some of Trial versions? It's something like beta releases, right?  I dont know, if it can be downgraded, so I want to make sure to not to mess anything.

![Screenshot_2023-11-04-20-43-47-935_com hlk hlkradartool](https://github.com/EverythingSmartHome/everything-presence-lite/assets/54975513/9d2369c4-dc4d-4bc7-8884-e4264552aa72)

**Comment by EverythingSmartHome** [comment]
Yeah you can try and download a beta, downgrading is possible

**Comment by kostda** [comment]
I upgraded to 2.04. I had some few miner problem with upgrading (had to start upgrade multiple times). But at the end it ended well.
I even get new detail info page in app. But still doesnt show any motion :(
![Screenshot_2023-11-04-21-14-06-668_com hlk hlkradartool](https://github.com/EverythingSmartHome/everything-presence-lite/assets/54975513/4588420f-ebc3-4ce7-98d7-5e8079aa1a22)

**Comment by kostda** [comment]
Now I also tried v2.02 and no change

**Comment by kostda** [comment]
Hi, do you have any other options? Sensor is still not working.

Thanks

**Comment by EverythingSmartHome** [comment]
Sorry for the delay, somehow I missed it!

If you can please get in touch with me using the contact page on the shop, then we can get you sorted out with a replacement: https://shop.everythingsmart.io/pages/contact

**Comment by kostda** [comment]
Hi, I ordered new sensor LD2450 and after replacing it started working. 

Thanks for trying to help me :)
