### ISSUE TITLE
Unable to add everything presence lite - 

### ISSUE THREAD

**Issue by williamjeccles** [EverythingSmartHome/everything-presence-lite#260]
So when plugging in the device to power, it appears within home assistant automatically.

When I click Add, I see the following spinner for a while
![image](https://github.com/user-attachments/assets/f3d489ac-6b01-47b6-acd5-b49327c02105)

Then the following error:
![image](https://github.com/user-attachments/assets/5f9fa073-867f-44ad-8ded-7e178c7caded)

Any ideas on what to do next?

**Comment by EverythingSmartHome** [comment]
Try restarting Home Assistant and try again

**Comment by williamjeccles** [comment]
done, no difference

**Comment by EverythingSmartHome** [comment]
Hmm strange, that bit is handled by Bluetooth on Home Assistant.

In that case I would try the manual setup process in the user guide, below the automatic setup section

**Comment by williamjeccles** [comment]
Updating the firmware and connecting via the manual method worked for me. Thanks
