### ISSUE TITLE
Exclusion zones query (more than 1)

### ISSUE THREAD

**Issue by phairplay** [EverythingSmartHome/everything-presence-lite#268]
Hi,
I've just taken delivery of your lite and it's really impressive, I have a query regarding exclusion zones.

It is possible to have more than 1 exclusion zone or am I missing something?

**Comment by EverythingSmartHome** [comment]
For the moment it's a single exclusion zone. It's a pretty new feature that can be a bit complex so for the moment a single has been implemented to ensure no bugs
