### ISSUE TITLE
Bluetooth keeps turning off

### ISSUE THREAD

**Issue by rjbutler** [EverythingSmartHome/everything-presence-lite#275]
Using the standard everything_presence_lite_ha.yaml, I find the mmwave_bluetooth switch keeps turning off.  I’m assuming that setting is required for it to be used as a bluetooth proxy?  Or am I mistaken.  Any idea why it gets turned off periodically?

**Comment by EverythingSmartHome** [comment]
If you flash Bluetooth proxy then it's always on with no way to turn it off.

The "mmWave Bluetooth" is the Bluetooth that's built into the LD2450 that's used for updating firmware. Recommend to leave it off unless your doing a firmware update

**Comment by rjbutler** [comment]
Ah, ok.  That makes sense.  I was sure when I first installed it that Bermuda BLE Triangulation didn’t see the EPL until I turned that on, but maybe it just took a while to refresh.  Thanks!
