### ISSUE TITLE
CMAKE error when trying to install via ESPHome in HA

### ISSUE THREAD

**Issue by CodebyADHawk** [EverythingSmartHome/everything-presence-lite#277]
When trying to install the latest version of ESPHome on a new EPL, I'm getting a CMAKE error part way through the process. The error is as follows:

INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/everything-presence-lite-REDACTEDMAC.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Compiling app...
Processing everything-presence-lite-REDACTEDMAC (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.6
INFO Installing esphome/noise-c @ 0.1.6
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.6 has been installed!
INFO noise-c@0.1.6 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.4
INFO Installing esphome/libsodium @ 1.10018.4
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.4 has been installed!
INFO libsodium@1.10018.4 has been installed!
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
Library Manager: Installing improv/Improv @ 1.2.4
INFO Installing improv/Improv @ 1.2.4
Unpacking  [####################################]  100%
Library Manager: Improv@1.2.4 has been installed!
INFO Improv@1.2.4 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
Reading CMake configuration...
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "/data/build/everything-presence-lite-REDACTEDMAC/.pioenvs/everything-presence-lite-60b33c/CMakeFiles/CMakeOutput.log".
See also "/data/build/everything-presence-lite-REDACTEDMAC/.pioenvs/everything-presence-lite-60b33c/CMakeFiles/CMakeError.log".

CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error in CMakeLists.txt:
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

========================== [FAILED] Took 4.72 seconds ==========================

This EPL is working and reporting in HA, but with the CMAKE error it seems it won't be able to be updated.

I tried reinstalling the firmware a couple times via the Chrome browser using the Getting Started guide. The firmware install and connecting to WiFi went fine, but I'm not able to manage the device firmware via ESPHome.

I also tried clearing the cleaning the build files before going through the install process in ESPHome, but I got the same error even after clearing the build files. Any advice on how to overcome this error is appreciated.

**Comment by EverythingSmartHome** [comment]
This is a problem with your local ESPHome compiler (which isn't needed btw unless you want to make manual changes to the config). Usually cleaning the build files is enough but you could try removing the add-on, reinstalling and trying again.

Since this isn't related to the Lite config and your able to install firmware from the website OK I'll close this as it's just an ESPHome compiler issue but hopefully clearing caches should help
