### ISSUE TITLE
Zones are not saving

### ISSUE THREAD

**Issue by GoBooth** [EverythingSmartHome/everything-presence-lite#278]
I just received my Everything Presence Lite, so far so good.
I’m downloaded the add-on to configure the zones.

doesn’t matter if I create 2, 3 or 4 zones, when I click on save, I get a pop-up that says it has saved succesfully, but then the GUI deletes all the zones I just created.

If I check the entities, the zones don’t exist in the esphome/everything lite.

What am I doing wrong?

I’m on Firmware: 1.2.0

![Everything Presence Lite](https://github.com/user-attachments/assets/00b75171-e655-44d0-ba6c-7cb269f58766)

**Comment by GoBooth** [comment]
ok I figured it out.

You need to **manually** enabled ALL the disabled entities related to all other zones (like 20 things)
and then when you create the zones, or more specificly, when you save the zones, "persistant" needs to be turned on.

**Comment by GoBooth** [comment]
ok I figured it out.

You need to manually enabled ALL the disabled entities related to all other zones (like 20 things)
and then when you create the zones, or more specificly, when you save the zones, "persistant" needs to be turned on.

**Comment by noisymime** [comment]
I think this needs to be made a bit more clear in either the Zones documentation or the Zone Configurator. The message saying it was saved is entirely wrong and very confusing trying to figure out what is happening. 

Ideally the Zone Configurator should enable the required zones when you hit save.
