### ISSUE TITLE
Wrong Firmware installed for EP Lite

### ISSUE THREAD

**Issue by actran** [EverythingSmartHome/everything-presence-lite#33]
I bought EP Lite and tried to install.    

I am on Lite documentation site, troubleshooting page.  When I clicked on Updating button on this URL:  https://everythingsmarthome.github.io/everything-presence-lite/troubleshooting.html, it actually installed the EP One firmware.

Where/how can I get EP Lite firmware?

**Comment by EverythingSmartHome** [comment]
Hi, you can find it here: https://everythingsmarthome.github.io/everything-presence-lite/updating.html

**Comment by actran** [comment]
Thanks Lewis.  You can close this issue.   You may want to update the "Updating" button at https://everythingsmarthome.github.io/everything-presence-lite/troubleshooting.html to correct URL.
