### ISSUE TITLE
Tuning the sensitivity

### ISSUE THREAD

**Issue by nilsi** [EverythingSmartHome/everything-presence-lite#38]
Hi! The sensor works great overall. But I have some problems detecting me in a big room (4x8 m where the sensor is placed in the middle of the 8m wall). When I'm in the corner on the opposite side of the sensor on the sofa it seems to have a problem detecting me.

I read in the wiki [here](https://everythingsmarthome.github.io/everything-presence-lite/tuning.html#sensitivity-and-latency) that I can configure the sensitivity. But I cant find the setting for doing this. Its not in the list:

Any ideas what I can do for a better performance?
<img width="347" alt="Screenshot 2023-11-12 at 22 44 42" src="https://github.com/EverythingSmartHome/everything-presence-lite/assets/793881/3e1108c5-7486-4a0e-9985-750003efed88">
<img width="332" alt="Screenshot 2023-11-12 at 22 44 33" src="https://github.com/EverythingSmartHome/everything-presence-lite/assets/793881/0adb18fe-cab6-4c90-916c-fd42efeb2d05">

Thanks

**Comment by EverythingSmartHome** [comment]
Hello! Unfortunately the Lite doesn't support sensitivity, this is something I need to remove from the Wiki.

That room is probably a bit too big for the Lite (at least a single lite, multiple would probably work), but you could try increasing the Occupancy off delay
