### ISSUE TITLE
Overhead mounting configuration?

### ISSUE THREAD

**Issue by ColdFireIce** [EverythingSmartHome/everything-presence-lite#66]
Hi,

I couldn't find anything about this in the manual:
Is there a good way to overhead mount this and setup zones? As there is only X and Y coordinates, and Y stays relatively constant in an overhead mounting position, I don't see how i could setup the zones?

Love the idea, ingenuity and initiative to sell this, even if, after shipping and customs to Germany (stupid Brexit), one sensor cost me 51€ 

Best regards!

PS. I had some problem connecting the senor to my WLAN, so i reflashed it, but this didn't work until i held down one of the buttons.
What are the two buttons for? I couldn't find any documentation or labeling?

**Comment by kloppy** [comment]
Overhead mounting would flip the x coordinate, but otherwise zones should still be usable. You would only lose an axis if you mounted sideways.
