### ISSUE TITLE
Can't connect to ESP. Please make sure your YAML file contains an 'api:' line.

### ISSUE THREAD

**Issue by ryanandrewbaker** [EverythingSmartHome/everything-presence-lite#68]
Installing either firmware (proxy or no proxy) I get the following error when trying to connect the EPL to home assistant manually. 

Can't connect to ESP. Please make sure your YAML file contains an 'api:' line.

The EPL is not autodiscovered by home assistant, although I can see it gets an IP on my router. So attempting to add it as an ESP32 device manually gets the above error.

**Comment by EverythingSmartHome** [comment]
If your getting that error then generally means you are using the incorrect IP address or the IP isn't accessible from Home Assistant. If auto discovery isn't working, is it on a different vlan and do any firewall rules apply?

**Comment by ryanandrewbaker** [comment]
Wow, immediate response, cheers!

I don't believe either of those is the case. The IP is what's reported by my google wifi in the home app, so I can't see how it'd be different. And the firewall in google wifi is also not configurable as far as i'm aware so there are no custom rules, it just... is. Hmmm. If it's my network, I may need to wait until I move and stop using google wifi then unless there are any other suggestions?

**Comment by EverythingSmartHome** [comment]
Is your Home Assistant server connected via the same router? From another machine, can you try running a ping to the Lites IP?

**Comment by ryanandrewbaker** [comment]
HA is wired, but same subnet as the Lite. Can def ping the EPL. Very strange. 

I'm switching to a full omada setup which will allow me better control and troubleshooting in a few weeks, I may just put the lite on the shelf until then and revisit. Thanks for getting back to me so quickly. Google wifi is... not great.

**Comment by Smiley1244** [comment]
I've just flashed my new lite via the website and i'm getting the same. I can confirm I'm manually trying to connect to the correct IP address and it is pingable from other machines on the network.

**Comment by Smiley1244** [comment]
I've reflashed again via the site and it's now working :)

**Comment by chondro878** [comment]
Please help as im seeing the same issue with 5 EPL devices. I feel people are seeing this and just "by luck" are able to resolve the issue!

**Comment by EverythingSmartHome** [comment]
Cross posting for others searching:

Chondro has Home Assistant on a different subnet to SSID they have connected their devices too. We have confirmed over email that Chondro's Home Assistant cannot ping devices on that SSID either because of a network misconfiguration or because of firewalls rules blocking access

Home Assistant needs to be able to communicate with devices across the network or the integration won't work

**Comment by HarvsG** [comment]
@EverythingSmartHome 
I am getting this issue even though I can ping the EPL from HA
![Image](https://github.com/user-attachments/assets/c5809963-3db9-459c-8d06-f9bbd3ec3f7c)
![Image](https://github.com/user-attachments/assets/44784e61-152f-4206-a582-1514fa3be0da)
![Image](https://github.com/user-attachments/assets/727c6e88-24fc-42a4-b4dc-a67db507cafe)
