### ISSUE TITLE
Zones Not Working Correctly

### ISSUE THREAD

**Issue by mark-mcdougall** [EverythingSmartHome/everything-presence-lite#73]
I have 2 everything presence lites - unfortunately I can't get either of them working correctly. 

EPL1: Running firmware 2023.12.8
EPL2: Running firmare 2023.12.9

What works on both devices:
Ocupancy
Target 1: Active, Angle, Distance, Resolution, Speed, 1 X, 1 Y (I haven't tested with multiple targets).

On each device I set up 2 zones and set the XY values of the top left and both right corners as per this video https://www.youtube.com/watch?v=W8vOWSbXzKY. The zones I have set appear correct (I took them from the device Target 1 X and Target 1 Y values as instructed in this video https://www.youtube.com/watch?v=wCwMNSeLRcw)

On EPL1:
Zone 1 occupancy shows as On but zone 2 never changes from Off. However looking at the Logbook it appears that both zone 1 and zone 2 occupancy sensors are being turned on and off but I can't see this from the device's screen in HA

On EPL2:
On the device screen neither zones' occupancy shows as on. Via the Logbook zone 1 shows as turning on and off but zone 2 just shows as going off and then to unavailable.

As I was having so much trouble I decided to download smarthomejunkie's blueprint to see if I could make any progress.
On EPL1, in the blueprint I set up the same 2 zones and set zone 1 to turn on/off light 1 and zone 2 to turn on/off light 2.
Weirdly the zone 2 blueprint automation worked but zone 1 did not. Even more strange was when I made a normal HA automation based off of the zone occupancy instead of the XY values, zone 1 worked but zone 2 didn't. 

This leads me to believe that for EPL1 there is an issue with the zone 1 XY values and the zone 2 occupancy sensor. I have set the XY values multiple times for both zones and have seen no improvement. Using the blueprint for zone 2, and automation for zone 1 kind of works but it is messy and the response time using the zone occupancy value is very slow compared to the XY values.

On EPL2 neither the blueprint or automations work for either zone.

I should note that for the blueprint I set the XY coordinates for the other 2 unused zones to zeroes and the triggered entities to None so that I didn't get an error when I tried to save the blueprint.

Has anyone experienced similar issues? I assume that I am not correctly setting up the zones.

I saw on the discord that some people had success switching the start and end x values - I tried this but had no success. This again suggests to me that I might have my coordinates set up incorrectly with my zone 1. Is there a better way to get the XY coordinates that using the 1 X, 1 Y values?

Anyone got any suggestions for what I can try to get these up and running?

**Comment by jonwork88** [comment]
Also not able to get the Zones to work.  
Device info
Everything_Presence_Lite
Firmware: 2023.12.9 
Hardware: 1.0.2 

Set up 2 zones.  Followed the instructions from the same videos listed above.  Input the coordinates from Top L and Bottom R for each Zone.    

The sensors read me, the main occupancy binary sensor reads me, but I don't register in any of the zones.

I Have tweaked my x,y's several times, and also switched where I take my readings (ie:  did from top R to Bottom L as well), doesn't appear to make a difference.  Rebooted the sensor after making changes... rebooted HA after making changes. 
 Not sure what else I can do.

Nothing in my EPL yaml about Zones (not sure if there is supposed to be).  

Are Zones not working right now?  Any suggestions?

Appreciate any help you can provide.

Thnx.  Jon

**Comment by EverythingSmartHome** [comment]
Hi guys (sorry I missed this when it was created)

Can you share some images of the coordinates and settings you are using?

**Comment by EverythingSmartHome** [comment]
Did you try switching the beginning and end X coordinates around?

**Comment by jonwork88** [comment]
only the x coordinates?  I changed both the x&y....  but not "just" the X

**Comment by jonwork88** [comment]
I flipped the coordinates and I have it "sometimes" registering, and how its registering brought up a thought.  

Will the "Zones" that are created off of the 2 sets of coordinates always be a perfect square/rectangle aligned with the orientation of the EPL?  If so, that might be part of my problem as I have it coming off a side wall at an angle, it its probably not able to create the zone I am looking for with only 2 sets of coordinates....  

Below are a couple of images that show the placement and ~ angle of the EPL and the type of rectangle I want, vs what I think "might" be happening...  Does that make sense?

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/47480708/74fb0075-9ac3-4060-8b27-dbc8a3c28d95)

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/47480708/16a7eb70-7267-480b-95a6-b1dba40733bc)

Thanks!  Jon

**Comment by EverythingSmartHome** [comment]
Yes the second image is correct with the coordinate system

**Comment by kloppy** [comment]
I have posted a modified package in #39 which includes rotated zones like in the first picture @jonwork88 posted, as I have also put my EPLs into corners. You could give it a try.

**Comment by neoKushan** [comment]
Hi,

I'm really struggling to understand how zones work and the coordinates behind them. I was hoping the EPL documentation would be updated to explain them but so far nothing.

Does anyone have a simple _written_ guide on how to set up and define zones?

**Comment by poker86** [comment]
Hello,
same here,  I guess I'm just not completely understanding this.  I feel like based on the plot map that I should have zone 1 and zone 2 with active occupancy. but I am not. 

Map:
![map](https://github.com/EverythingSmartHome/everything-presence-lite/assets/161692779/db655816-2fc4-49ae-adf5-180b45d2c820)
Sensors:
![sensors](https://github.com/EverythingSmartHome/everything-presence-lite/assets/161692779/9762fdb0-5599-4548-ad59-ef54a6fcabc1)

**Comment by EverythingSmartHome** [comment]
What is the actual zone settings here as they aren't shown? 

Do you have the start and end X values the right way around with regards to negative and positive numbers?

**Comment by poker86** [comment]
Controls
![controls](https://github.com/EverythingSmartHome/everything-presence-lite/assets/161692779/eb43730e-c94f-4d96-bf7a-ef30ed059cfa)

**Comment by EverythingSmartHome** [comment]
Try swapping the start X and end X values around as mentioned

**Comment by kloppy** [comment]
@poker86 how did you setup that neat map showing zone and target?

**Comment by poker86** [comment]
it was the Pull Resquest post by @obbers

https://github.com/EverythingSmartHome/everything-presence-lite/pull/57

**Comment by poker86** [comment]
@EverythingSmartHome, and thank you for helping me with zones. that indeed worked. and also making a great product

**Comment by bikeymouse** [comment]
> @poker86 how did you setup that neat map showing zone and target?

I have also used this map representation, but found out that [it has mirrored the x-axis](https://github.com/EverythingSmartHome/everything-presence-lite/pull/57#issuecomment-2227444755), so that could explain your issues.

**Comment by neoKushan** [comment]
> Hi,
> 
> I'm really struggling to understand how zones work and the coordinates behind them. I was hoping the EPL documentation would be updated to explain them but so far nothing.
> 
> Does anyone have a simple _written_ guide on how to set up and define zones?

So uhh...is there no written documentation anywhere on this feature? I still haven't got it to work and I'm struggling with where to even begin.

**Comment by klaneos** [comment]
I have this same zone problem with the latest EPL. Will keep an eye on this issue in case there are any more developments on the fix. Preferably EPL update fix

**Comment by EverythingSmartHome** [comment]
> > Hi,
> > I'm really struggling to understand how zones work and the coordinates behind them. I was hoping the EPL documentation would be updated to explain them but so far nothing.
> > Does anyone have a simple _written_ guide on how to set up and define zones?
> 
> So uhh...is there no written documentation anywhere on this feature? I still haven't got it to work and I'm struggling with where to even begin.

Sorry didn't see this, can you share the settings you have and where you are running into issues?

**Comment by EverythingSmartHome** [comment]
> I have this same zone problem with the latest EPL. Will keep an eye on this issue in case there are any more developments on the fix. Preferably EPL update fix

What's the issue? Can you share the zone configs?

**Comment by neoKushan** [comment]
> > > Hi,
> > > I'm really struggling to understand how zones work and the coordinates behind them. I was hoping the EPL documentation would be updated to explain them but so far nothing.
> > > Does anyone have a simple _written_ guide on how to set up and define zones?
> > 
> > 
> > So uhh...is there no written documentation anywhere on this feature? I still haven't got it to work and I'm struggling with where to even begin.
> 
> Sorry didn't see this, can you share the settings you have and where you are running into issues?

Hi, thanks for the response. I was hoping for some documentation on how zones are meant to be set up, ideally with some examples because I'm failing at the first hurdle.

I'll explain what I am trying to achieve, because I think (hope) that what I am trying to do is actually quite straightforward but I'm not clear at all how the Zone X/Y Begin/End values are meant to be applied.

Here's a diagram of the room I am trying to zone:

![Diagram](https://github.com/user-attachments/assets/6380d344-df13-4e76-97cb-c99140ddabd3)

This is taken from the floor plans so the outer dimensions are relatively accurate. The Everything Presence Lite is mounted high up at the top of the image, it's facing down into the room at about a 45 degree angle.

The problem I am trying to solve is that when sat at my desk, I'm slightly too warm but when sat on the sofa I am slightly too cold - thanks to the aircon being positioned in the corner as shown. All I want to do is adjust the temperature by a degree if someone is on the sofa. Or in other words, detect if someone is in the Red zone (Call that Zone 1) or the yellow Zone (Call that zone 2) or both. The automation part I can handle easily enough, but as for which values I have to use to achieve this, I am not even sure where to begin as there's no way that I can tell to "visualise" what the sensor is seeing.

I'm aware that the sensor is going to see in a sort of "arc" pattern but I'm not entirely clear on the size of that arc, or where the zone coordinates fall in the arc.

The only setting for the EPL I'm relatively certain of is "Max Distance", which I have set to 400cm as that's the length of the room, but where I go next I am not sure.

I hope the above makes sense?

**Comment by EverythingSmartHome** [comment]
Please see the new docs for the zone and the new visual zone configurator too which I believe will help with this: https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/creating-zones.html
