### ISSUE TITLE
Firmware update?

### ISSUE THREAD

**Issue by auanasgheps** [EverythingSmartHome/everything-presence-lite#76]
Hi,
This is not a proper issue but there's no "discussion" section, so I'm posting it here

This is my Everything Presence Lite:
![immagine](https://github.com/EverythingSmartHome/everything-presence-lite/assets/20586878/2035d7f5-dda0-4e0d-82ee-278853c0d41b)

On GitHub I see a 1.0.2 release. Am I supposed to see this update in HA or do it manually?

**Comment by EverythingSmartHome** [comment]
No unfortunately releases from GitHub won't show in Home Assistant. The only update you will see is an ESPHome update whichever will show in Home Assistant, but this is notifying you of a new ESPHome version, not necessarily a new Lite versison

**Comment by auanasgheps** [comment]
So "Hardware" version is in fact the EP Lite version?

I have to update manually connecting the sensor to a PC?

**Comment by auanasgheps** [comment]
Thank you, it worked! I was able to update it, although now shows 1.0.3 which I can't see anywhere!

**Comment by EverythingSmartHome** [comment]
Nice, glad it worked!
