### ISSUE TITLE
Target information not resetting to 0

### ISSUE THREAD

**Issue by murray-m17** [EverythingSmartHome/everything-presence-lite#77]
A few times this week I have noticed that targets 2 & 3 have not been resetting to 0 after the person leaves the area, so the distance, y pos, etc have just been stuck at the same value. ![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/156252504/e8ab29de-043c-4cc1-a00a-d58e6dc00c44) ![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/156252504/86ef3616-1579-4274-973a-2dfd361f164b)

**Comment by EverythingSmartHome** [comment]
I believe this should be resolved but let me know if still an issue
