### ISSUE TITLE
Tracker only shows 1 person

### ISSUE THREAD

**Issue by howesey2k** [EverythingSmartHome/everything-presence-lite#98]
Hi, am I doing something wrong? My device only appears to show information for one person when there are two people in the same zone?

Many thanks

**Comment by EverythingSmartHome** [comment]
Are the two people very close together? If so, it can be easy to detect as one target. You have no target 2 tracking info showing so it will always show one in the zone.

If not, you can try updating the firmware on the mmWave sensor to version 2.04 using the HLKRadarTool app on iOS or Android. It's a little clunky but fairly straightforward to get the firmware updated.

Let me know how it goes
